theme: jekyll-theme-cayman
title: Hannah's page
description: Website project for Computers and Language
github:
  Basic Words and Phrases: page2.html
  Tourist Vocabulary: page3.html
  Music: page4.html
  Top Tips: page5.html

